CREATE TABLE CHESSCLUB (
           ID INT,
           FIRST_NAME TEXT,
           LAST_NAME TEXT,
           GRADE INTEGER
       );
INSERT INTO "CHESSCLUB" VALUES(10518,'Jana','Deshpande',8);
INSERT INTO "CHESSCLUB" VALUES(10519,'Marcin','Lawler',8);
INSERT INTO "CHESSCLUB" VALUES(10520,'Ade','Khandelwal',7);
INSERT INTO "CHESSCLUB" VALUES(10521,'Keaton','Putra',7);
INSERT INTO "CHESSCLUB" VALUES(10532,'First','Friend',6);
INSERT INTO "CHESSCLUB" VALUES(10533,'Mehmet','Hogg',6);


CREATE TABLE DRAMACLUB (
           ID INT,
           FIRST_NAME TEXT,
           LAST_NAME TEXT,
           GRADE INTEGER
       );
INSERT INTO "DRAMACLUB" VALUES(10530,'Eslam','Chester',8);
INSERT INTO "DRAMACLUB" VALUES(10531,'Stavros','Orozco',7);
INSERT INTO "DRAMACLUB" VALUES(10532,'First','Friend',7);
INSERT INTO "DRAMACLUB" VALUES(10533,'Mehmet','Hogg',6);


CREATE TABLE TRACKFIELD (
           ID INT,
           FIRST_NAME TEXT,
           LAST_NAME TEXT,
           GRADE INTEGER
       );
INSERT INTO "DRAMACLUB" VALUES(10530,'Eslam','Chester',8);
INSERT INTO "CHESSCLUB" VALUES(10520,'Ade','Khandelwal',7);
INSERT INTO "TRACKFIELD" VALUES(10715,'Prashanth','Bajwa',6);
INSERT INTO "TRACKFIELD" VALUES(10716,'Darya','Sargent',6);
